version: '3.8'

services:
  db:
    image: postgres:15-alpine # Using PostgreSQL 15 on Alpine Linux
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist data
    environment:
      - POSTGRES_DB=assessment_db
      - POSTGRES_USER=assessment_user
      - POSTGRES_PASSWORD=assessment_pass # Change this in a real project!
    ports:
      - "5432:5432" # Expose PostgreSQL port to host (optional, for direct DB access)

  web:
    build: . # Build the image from the Dockerfile in the current directory
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/ # Mount current directory to app directory in container for live code reloading
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=assessment_db
      - DB_USER=assessment_user
      - DB_PASS=assessment_pass
      - DB_HOST=db # This is the service name of our postgres container
      - DB_PORT=5432
    depends_on:
      - db # Wait for the db service to be ready

volumes:
  postgres_data: # Defines a named volume for data persistence