name: Django CI Build Docker Image

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Triggers the workflow on push events to the main branch
  pull_request:
    branches: [ main ] # Optionally, also trigger on pull requests to the main branch

jobs:
  build_docker_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4 # It's good practice to use the latest stable version

      # Step 2: Set up Docker Buildx
      # Buildx is a Docker CLI plugin that extends the docker command with the full support of the features provided by Moby BuildKit.
      # This allows for more advanced building options, like building multi-platform images.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: (Optional) Login to a Docker registry
      # If you plan to push your image to Docker Hub, GitHub Container Registry, or another registry,
      # you'll need to log in. Replace with your registry details and store credentials securely using GitHub secrets.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image
      # This step uses the Dockerfile in the root of your repository.
      # Replace 'your-docker-image-name' with the desired name for your image.
      # You can tag it with the GitHub SHA for versioning.
      - name: Build Docker image
        run: docker build ./Day7-Github-Actions-and-Docker/bsu_redacted_module \
            --file ./Day7-Github-Actions-and-Docker/bsu_redacted_module/Dockerfile \
            --tag clarenzmauro/bsu-redacted-module:${{ github.sha }} \
            --push

      # Step 5: (Optional) Push the Docker image to the registry
      # This step pushes the built image. It only runs if the login step (if used) was successful.
      # - name: Push Docker image
      #   run: docker push github-actions-and-docker:${{ github.sha }}